description: 'Simple Magazine-Style Page'
title : Jekyll Chop-Shop
year : 2024

markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
plugins: [jekyll-gist]
permalink: /:categories/:title.html # year can be used for ordering
